<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net10.0-windows7.0</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Extended.Wpf.Toolkit" Version="5.0.0" />
    <PackageReference Include="FontAwesome5" Version="2.1.11" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Controls\XTextBox.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\XTextBoxBorder.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Controls\XTextBoxFolating.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="UserControls\UC_Header.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Images\Close.png" />
    <Resource Include="Images\CloseWhite.png" />
    <Resource Include="Images\Maximize.png" />
    <Resource Include="Images\minus.png" />
  </ItemGroup>

</Project>
